In [2]:
# Import for Neural Network
from NeuralNetwork import MultiLayerPerceptron as mlpLib
from sklearn import datasets

import numpy as np


# After dev. remove it!!!
# How create a MLP object
mlp = mlpLib.MLP(rng=np.random.RandomState(), n_in=4, n_hidden=[10, 9, 9, 11], n_out=3)

In [2]:
# How create a MLP object
#mlp = mlpLib.MLP(rng=np.random.RandomState(), n_in=4, n_hidden=[10, 9, 9, 11], n_out=3)

In [8]:
# load data
iris = datasets.load_iris()
input = np.array(iris.data[1:3,:])
print 'Input: \n', input

# propagating input throught each layer

# input layer
print '\nmlp.InputLayer.GetOutput(input): \n',mlp.InputLayer.GetOutput(input).eval()
input_output = mlp.InputLayer.GetOutput(input).eval()

# all hidden layers
# hidden 0 layer
print '\nmlp.HiddenLayer[0].GetOutput(input).eval(): \n',mlp.HiddenLayer[0].GetOutput(input_output).eval()
hidden_output = mlp.HiddenLayer[0].GetOutput(input_output).eval()

# output layer
#print '\nmlp.OutputLayer.GetOutput(hidden_output).eval(): \n',mlp.OutputLayer.GetOutput(hidden_output).eval()

# mlp object
print '\nmlp.GetOutput(input,show=False): \n',mlp.GetOutput(input).eval()

Input: 
[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]

mlp.InputLayer.GetOutput(input): 
[[ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]]

mlp.HiddenLayer[0].GetOutput(input).eval(): 
[[ 0.99995102  0.78557752  0.40869636 -0.99984988  0.87778838 -0.09019301
  -0.99822116  0.99942329 -0.64216613  0.96069918]
 [ 0.99994577  0.69814439  0.43856452 -0.9998155   0.85881802 -0.19581742
  -0.99826683  0.9993947  -0.62315505  0.96619594]]

mlp.GetOutput(input,show=False): 
[[ 0.40342941  0.39027086 -0.3065106 ]
 [ 0.37674415  0.41387543 -0.30746338]]


In [14]:
# Test L1Regularization
print "L1Reg: ", mlp.GetL1Reg().eval()

# Test L2Regularization
print "L2Reg: ", mlp.GetL2Reg().eval()

L1Reg:  37.6365235788
L2Reg:  14.9499002152


In [3]:
from sklearn import datasets

from NeuralNetwork import MultiLayerPerceptron

iris = datasets.load_iris()
X = iris.data
Y = iris.target

target = np.zeros([X.shape[0],3])

for i in xrange(X.shape[0]):
    target[i,Y[i]] = 1

trn_params = mlpLib.TrainParameters()

mlp.Train(X,Y,trn_params)


Train Function
Starting Train Process with the follow parameters:
Performance Function:  mse
L1 Regularization Value:  0.0
L2 Regularization Value:  0.0001
Number of Epochs:  10
Learning Rate:  0.01
Batch Size:  10
Train Indeces:  None
Test Indeces:  None
Validation Indeces:  None
Percentage of Train Events:  0.5
Percentage of Test Events:  0.25
Percentage of Validation Events:  0.25


TypeError: Cannot convert Type TensorType(int64, vector) (of Variable Subtensor{int64:int64:}.0) into Type TensorType(int32, vector). You can try to manually convert Subtensor{int64:int64:}.0 into a TensorType(int32, vector).